### ISSUE TITLE
20190315 - grant后是否需要flush privileges - qiaosong

### ISSUE THREAD

**Issue by chzhiyi** [chzhiyi/-KnowledgeShare#33]
网上一般的理解是修改权限grant后，是一定要flush privileges的。为什么呢？主要是为了保持权限在磁盘和内存的一致性。假如grant后是一致的，其实也没必要在flush privileges。而所谓的不一致，一般是由于误操作引起的。
## 全局权限
![全局权限](https://user-images.githubusercontent.com/20433003/54411532-bc02a800-472a-11e9-936f-85e2442b02f7.jpg)
```
# 会在磁盘和内存中同时插入数据，disk为mysql.user，mem为acl_users中添加一个acl_user对象。
mysql> create user 'qs'@'%' identified by 'qs';
Query OK, 0 rows affected (0.00 sec)

mysql> select t.* from mysql.user t where t.user='qs'\G
*************************** 1. row ***************************
                  Host: %
                  User: qs
           Select_priv: N
           Insert_priv: N
           Update_priv: N
           Delete_priv: N
           Create_priv: N
             Drop_priv: N
           Reload_priv: N
         Shutdown_priv: N
          Process_priv: N
             File_priv: N
            Grant_priv: N
       References_priv: N
            Index_priv: N
            Alter_priv: N
          Show_db_priv: N
            Super_priv: N
 Create_tmp_table_priv: N
      Lock_tables_priv: N
          Execute_priv: N
       Repl_slave_priv: N
      Repl_client_priv: N
      Create_view_priv: N
        Show_view_priv: N
   Create_routine_priv: N
    Alter_routine_priv: N
      Create_user_priv: N
            Event_priv: N
          Trigger_priv: N
Create_tablespace_priv: N
              ssl_type:
            ssl_cipher:
           x509_issuer:
          x509_subject:
         max_questions: 0
           max_updates: 0
       max_connections: 0
  max_user_connections: 0
                plugin: mysql_native_password
 authentication_string: *5B9E9DAAD2D1AD00E6D25C667B2E4EFD165CA560
      password_expired: N
 password_last_changed: 2019-03-15 13:23:23
     password_lifetime: NULL
        account_locked: N
1 row in set (0.00 sec)
```
